Columns: Home Visitor Closing Over/Under Week Date Year

Overall: the program should return a percent explaining how confident it is that it will be Overall/Under

In [ ]:
import requests
import re
from bs4 import BeautifulSoup
import pandas as pd

In [133]:

year = 2018# float('nan')
week = 1#float('nan')
df = pd.DataFrame([], columns= ["date", "homeTeam", "homeTeamPTS", "awayTeam",'awayTeamPTS','Over/Under'])
temp_arr = []
for week in range(1,18):
    url = 'https://www.pro-football-reference.com/years/'+str(year)+'/week_'+str(week)+'.htm'
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    soup1 = soup.find_all('div', class_='game_summary expanded nohover')
    for el in soup1:
        soup2 = el.find_all('table', class_='teams')
        for el2 in soup2:
            soup3 = el2.find_all('td')
            date = str(re.findall('>[A-Z].*<', str(soup3[0]))[0])[1:-1]
            team1 = str(re.findall('>[A-Z][a-z]* [A-Z][a-z]*',str(soup3[1]))[0])[1:]
            team1_points = str(re.findall('>\d+',str(soup3[2]))[0])[1:]
            ou_url = 'https://www.pro-football-reference.com/boxscores/'+str(re.findall('\d{9}.+.htm',str(soup3[3]))[0])
            r2 = requests.get(ou_url)
            soup4 = BeautifulSoup(r2.content, 'html.parser')
            soup5 = soup4.find('div',class_="content_grid")
            soup6 = str(soup5.find('div'))
            ou = re.findall('\d.+ ', str(re.findall('Over/Under.* ',soup6)))[0][:-1]
            temp_arr.append(ou_url)
            team2 = str(re.findall('>[A-Z][a-z]* [A-Z][a-z]*',str(soup3[4]))[0])[1:]
            team2_points = str(re.findall('>\d+',str(soup3[5]))[0])[1:]
            temp_series = pd.Series([date,team2,team2_points, team1,team1_points, ou], df.columns)
            df = df.append(temp_series, ignore_index=True)
display(df)

,date,homeTeam,homeTeamPTS,awayTeam,awayTeamPTS,Over/Under
0,"Sep 6, 2018",Philadelphia Eagles,18,Atlanta Falcons,12,44.5
1,"Sep 9, 2018",Cleveland Browns,21,Pittsburgh Steelers,21,41.0
2,"Sep 9, 2018",Baltimore Ravens,47,Buffalo Bills,3,39.0
3,"Sep 9, 2018",New York,15,Jacksonville Jaguars,20,43.0
4,"Sep 9, 2018",New England,27,Houston Texans,20,49.5
...,...,...,...,...,...,...
251,"Dec 30, 2018",Los Angeles,48,San Francisco,32,49.5
252,"Dec 30, 2018",Pittsburgh Steelers,16,Cincinnati Bengals,13,45.0
253,"Dec 30, 2018",Minnesota Vikings,10,Chicago Bears,24,40.5
254,"Dec 30, 2018",Kansas City,35,Oakland Raiders,3,52.5
255,"Dec 30, 2018",Tennessee Titans,17,Indianapolis Colts,33,42.5

In [134]:
pd.read_csv('data.csv')